default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: meal_book
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: meal_book_development

test:
  <<: *default
  database: meal_book_test

production:
  <<: *default
  database: meal_book_production
  username: meal_book
  password:
